# Generated by Django 5.1.2 on 2024-11-13 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_calendariofiltrado_calendariogeral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalendarioFiltrado',
        ),
        migrations.DeleteModel(
            name='CalendarioGeral',
        ),
        migrations.AddField(
            model_name='professor',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aula',
            name='curso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aula',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aula',
            name='periodo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aula',
            name='sala',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aula',
            name='turno',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite')], max_length=10),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='professor',
            name='disponibilidade',
            field=models.BooleanField(default=False),
        ),
    ]
